linters:
  enable-all: true

  disable:
    - interfacer
    - maligned
    - scopelint
    - exhaustivestruct
    - golint
    - wrapcheck
    - ireturn
    - gomnd
    - gci
    - exhaustruct
    - wsl
